apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
      - name: hello-world-python-container
        image: shoom818/harnessdocker:31
        ports:
        - containerPort: 80
