apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
      - name: hello-world-python-container
        image: {{.Values.image}}
        # image: <+artifact.image>
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort # Change to LoadBalancer if you're on a cloud platform and want an external IP
  selector:
    app: hello-world-python
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30003